export const ReducerCases = {
    SET_ACCOUNT_INFO: "SET_ACCOUNT_INFO",
    SET_PROFILE: "SET_PROFILE",
    SET_RECOMMEND_ITEMS: "SET_RECOMMEND_ITEMS",
    SET_HIGH_RATING_ITEMS: "SET_HIGH_RATING_ITEMS",
    RESET_STATE: "RESET_STATE",
}