export const ReducerCases = {
    SET_ACCOUNT_INFO: "SET_ACCOUNT_INFO",
    SET_PROFILE: "SET_PROFILE",
    SET_RECOMMEND_ITEMS: "SET_RECOMMEND_ITEMS",
    SET_HIGH_RATING_ITEMS: "SET_HIGH_RATING_ITEMS",
    SET_USER_ROLE: "SET_USER_ROLE",
}